id: htps://overturemaps.org/schema
name: schema
imports: geometry

classes:
  feature:
    abstract: true
    slots:
      - id
      - type
      - geometry
      - version
      - theme

  building:
    is_a: feature
    slot_usage:
      theme:
        range: theme_buildings

  building_part:
    is_a: feature
    slot_usage:
      theme:
        range: theme_buildings

slots:
  id:
    identifier: true
    slot_uri: schema:id
    required: true
    range: uuid
    description: Unique ID of the feature
  geometry:
    slot_uri: schema:geometry
    required: true
    range: geometry
    description: OGC simple geometry of the feature
  theme:
    slot_uri: schema:theme
    required: true
    range: theme
    description: Overture theme this feature type belongs to
  type:
    slot_uri: schema:type
    required: true
    designates_type: true
    range: string
    description: Feature type, e.g. building or place
  version:
    slot_uri: schema:version
    required: true
    range: integer_positive
    description: >-
        Version number of the feature, incremented in each Overture
        release where the geometry or attributes of the feature
        changed.

types:
  integer_positive:
    base: int
    minimum_value: 1
    description: An integer greater than or equal to 1
  string:
    base: str
    description: Any string value
  uuid:
    base: str
    pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    description: Universally Unique Identifier (UUID)

enums:
  theme:
    description: Overture theme, e.g. buildings or transportation
    permissible_values:
      addresses:
      buildings:
  theme_buildings:
    description: Narrows the theme enumeration to just the buildings theme
    permissible_values:
      buildings:
