id: htps://overturemaps.org/schema
name: schema
imports: geometry

classes:
  feature:
    abstract: true
    slots:
      - id
      - type
      - geometry

  building:
    is_a: feature

  building_part:
    is_a: feature

slots:
  id:
    identifier: true
    slot_uri: schema:id
    required: true
    range: uuid
    description: Unique ID of the feature
  type:
    slot_uri: schema:type
    required: true
    designates_type: true
    range: string
    description: Feature type, e.g. building or place
  geometry:
    slot_uri: schema:geometry
    required: true
    range: geometry
    description: OGC simple geometry of the feature

types:
  string:
    base: str
    description: Any string value
  uuid:
    base: str
    pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    description: Universally Unique Identifier (UUID)
