id: htps://overturemaps.org/schema
name: schema

classes:
  feature:
    slots:
      - id
      - type

slots:
  id:
    identifier: true
    slot_uri: schema:id
    required: true
    range: uuid
    description: Unique ID of the feature
  type:
    slot_uri: schema:type
    required: true
    range: type
    description: Feature type, e.g. building or place

types:
  uuid:
    base: str
    pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    description: Universally Unique Identifier (UUID)

enums:
  type:
    description: Type of Overture feature
    permissible_values:
      building:
      building_part:
